FROM nginx
MAINTAINER john john@sharelug.com
#RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
#COPY config/cert.pem /etc/nginx/cert.pem
#COPY config/privkey.pem /etc/nginx/privkey.pem
#COPY config/chained.crt /etc/nginx/chained.crt